name: "Build Netflix unlock docker"

on:
  workflow_dispatch:

jobs:
  Building:
      runs-on: ubuntu-latest
      name: "Build Netflix unlock docker"
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/netflix_unlock:latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

