name: "Build and push images"

on:
  workflow_dispatch:

jobs:
  Building:
      runs-on: ubuntu-latest
      name: "Build Netflix unlock docker"
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/netflix_unlock:latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Build Netflix unlock docker 
          run: |
            
            export DOCKER_CLI_EXPERIMENTAL=enabled

            docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d

            docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}

            docker buildx create --use --name mybuilder

            docker buildx inspect mybuilder --bootstrap

            docker buildx build --tag ${DOCKERHUB_REPOSITORY} --platform=linux/arm64,linux/amd64 . --push
