name: "Build Netflix unlock docker"

on:
  workflow_dispatch:

jobs:
  Building:
      runs-on: ubuntu-latest
      name: "Build Netflix unlock docker"
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/netflix_unlock:latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        - run: docker buildx build -t ${DOCKERHUB_REPOSITORY} --platform=linux/arm64,linux/amd64 . --push
